### PR TITLE
Fix lua config

### PR DESCRIPTION
**Pull request by andreifilip123**
Hello! I tried configuring this locally and after a while of figuring out how to work with LUA (😅), I noticed 2 errors in the current lua init. 
1. css modules language server name is wrong (should be cssmodules_ls)
2. the update_capabilities function has been deprecated and should be replaced with default_capabilities:
https://www.reddit.com/r/neovim/comments/y97pl3/cmp_nvim_lspupdate_capabilities_is_deprecated_use/

### CODE REVIEW

**Comment by oasido** [comment]
**Completely** new to Neovim here.
I edited my files to match this pull request, and I'm having issues with Replace update_capabilities with default_capabilities.
Getting this error on launch:
```
E5113: Error while calling lua chunk: /home/oasido/.config/nvim/lua/trash/lsp/init.lua:50: attempt to call field 'default_capabilities' (a nil value)
stack traceback:
        /home/oasido/.config/nvim/lua/trash/lsp/init.lua:50: in main chunk
        [C]: in function 'require'
        /home/oasido/.config/nvim/init.lua:21: in main chunk
```

**Comment by andreifilip123** [comment]
Yeah, I get the same error now. Not sure why. Initially I didn't but now I do

**Comment by oasido** [comment]
Managed to get it working with this configuration:
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = cmp_nvim_lsp.default_capabilities
```

**Comment by andreifilip123** [comment]
You're right, that works. Thank you !

**Comment by andreifilip123** [comment]
Closed since #4 fixed it

**Pull request closed without merging**
